function defaultSettings
%This function recreates the settings.mat file with the default settings in
%this script

baseLocationsRig = zeros(9,3); %base locations
rigOrigin = [60 10 50]; %vector to rig origin in camera (cam) cordinates (cm)
markDistFromCoM = [1.25 1.25]; %dist from fore and aft marks (respectivly) from center of mass of turbine (cm)
FoV = [37.5 23.24]; %full horizontal and vertical angular FoV (degrees)
Cp = 0.5; %Cp of system
kParms = [-0.0026,-0.2848,0.2755,-0.0759,0.1403]; %constants for paramterization of Cl and Cd [k0 k1 k0_bar k1_bar k2_bar]
rho = 1000; %density of working fluid (kg/m^3)
Fb = 0.0997; %net bouyant force (N)
dragScreenDia = 0.06; %diameter of drag screen (m)
freestreamVelocity = 0.2; %m/sec
distToGlass = 30; %cm
n1 = 1.00029; %index of refraction for air
n2 = 1.33; %index of refraction for water

programSettings = struct('baseLocationsRig',baseLocationsRig,...
    'distToRigOrigin',rigOrigin,...
    'markDistFromCoM',markDistFromCoM,...
    'FoV',FoV,...
    'Cp',Cp,...
    'kParms',kParms,...
    'rho',rho,...
    'Fb',Fb,...
    'dragScreenDia', dragScreenDia,...
    'freestreamVelocity', freestreamVelocity,...
    'distToGlass',distToGlass,...
    'n1', n1,...
    'n2', n2);

save(fullfile(cd, 'Settings','programSettings.mat'),'programSettings');

end

